import { useContext } from "react";
import { GetServerSideProps } from "next";
import Head from "next/head";
import { Header, Hero, Modal, Raw, SubscriptionPlan } from "src/components";
import { AuthContext } from "src/context/auth.context";
import { IMovie } from "src/interfaces/app.interface";
import { API_REQUEST } from "src/services/api.service";
import { useInfoStore } from "src/store";

export default function Home({
  trending,
  topRated,
  tvTopRated,
  popular,
  documentary,
  family,
  comedy,
  history,
}: HomeProps): JSX.Element {
  const { modal } = useInfoStore();
  const { isLoading } = useContext(AuthContext);
  const subscription = false;

  if (isLoading) return <>{null}</>;

  if (!subscription) return <SubscriptionPlan />;

  return (
    <div
      className={`relative min-h-screen ${
        modal && "!h-screen overflow-hidden"
      }`}>
      <Head>
        <title>Movie App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Header />
      <main className="relative pl-4 pb-24 lg:space-y-24 lg:pl-16">
        {/* Hero */}
        <Hero trending={trending} />
        <section className="flex flex-col gap-[80px]">
          {/* Raw */}
          <Raw title={"Top Rated"} movies={topRated} />
          <Raw title={"TV Show"} movies={tvTopRated} isBig={true} />
          <Raw title={"Popular"} movies={popular} />
          <Raw
            title={"Documentary"}
            movies={documentary.reverse()}
            isBig={true}
          />
          <Raw title={"Comedy"} movies={comedy} />
          <Raw title={"Family"} movies={family} />
          <Raw title={"History"} movies={history.reverse()} />

          {/* BigRaw */}
          {/* Raw */}
          {/* BigRaw */}
        </section>
      </main>
      {modal && <Modal />}
    </div>
  );
}

export const getServerSideProps: GetServerSideProps<HomeProps> = async () => {
  const [
    trending,
    topRated,
    tvTopRated,
    popular,
    documentary,
    comedy,
    family,
    history,
  ] = await Promise.all([
    fetch(API_REQUEST.trending).then((res) => res.json()),
    fetch(API_REQUEST.top_rated).then((res) => res.json()),
    fetch(API_REQUEST.tv_top_rated).then((res) => res.json()),
    fetch(API_REQUEST.popular).then((res) => res.json()),
    fetch(API_REQUEST.documentary).then((res) => res.json()),
    fetch(API_REQUEST.comedy).then((res) => res.json()),
    fetch(API_REQUEST.family).then((res) => res.json()),
    fetch(API_REQUEST.history).then((res) => res.json()),
  ]);

  return {
    props: {
      trending: trending.results,
      topRated: topRated.results,
      tvTopRated: tvTopRated.results,
      popular: popular.results,
      documentary: documentary.results,
      comedy: comedy.results,
      family: family.results,
      history: history.results,
    },
  };
};

interface HomeProps {
  trending: IMovie[];
  topRated: IMovie[];
  tvTopRated: IMovie[];
  popular: IMovie[];
  documentary: IMovie[];
  comedy: IMovie[];
  family: IMovie[];
  history: IMovie[];
}
